import type { Metadata } from "next"
import { Inter, Pixelify_Sans, Chakra_Petch } from "next/font/google"
import "./globals.scss"
import Navbar from "@/components/Navbar/Navbar"
import Providers from "./providers"

const inter = Inter({ subsets: ["latin"] })
// const pixel = Chakra_Petch({ subsets: ["latin"], weight: ['300', '400', '500', '600'] })

export const metadata: Metadata = {
  title: "Bixel",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  )
}
